//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AporteEmpleador
    {
        public int IdAporteEmpleador { get; set; }
        public string CodApo { get; set; }
        public string Aporte { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
    }
}
