//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiasLaborable
    {
        public int IdDiasLaborables { get; set; }
        public string CodMes { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<byte> DiasLab { get; set; }
        public string Cerrado { get; set; }
    }
}
