//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FondoPensione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FondoPensione()
        {
            this.Personals = new HashSet<Personal>();
            this.PlanillasRems = new HashSet<PlanillasRem>();
        }
    
        public int IdFondoPen { get; set; }
        public string CodFon { get; set; }
        public string Entidad { get; set; }
        public Nullable<decimal> ApoOblF { get; set; }
        public Nullable<decimal> ComVarF { get; set; }
        public Nullable<decimal> PriSegF { get; set; }
        public Nullable<decimal> ApoOblM { get; set; }
        public Nullable<decimal> ComVarM { get; set; }
        public Nullable<decimal> PriSegM { get; set; }
        public Nullable<decimal> PorONP { get; set; }
        public Nullable<byte> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillasRem> PlanillasRems { get; set; }
    }
}
