//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliclinicoNuevoEntities2 : DbContext
    {
        public PoliclinicoNuevoEntities2()
            : base("name=PoliclinicoNuevoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AporteEmpleador> AporteEmpleadors { get; set; }
        public virtual DbSet<AreaAnalisi> AreaAnalisis { get; set; }
        public virtual DbSet<AreaLaboratorio> AreaLaboratorios { get; set; }
        public virtual DbSet<AreaServicio> AreaServicios { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<DiasLaborable> DiasLaborables { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<FondoPensione> FondoPensiones { get; set; }
        public virtual DbSet<Medico> Medicos { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<PlanillasRem> PlanillasRems { get; set; }
        public virtual DbSet<Procedimiento> Procedimientoes { get; set; }
        public virtual DbSet<TablaAnalisi> TablaAnalisis { get; set; }
        public virtual DbSet<TablaAnalisisVR> TablaAnalisisVRs { get; set; }
        public virtual DbSet<Ubigeo> Ubigeos { get; set; }
        public virtual DbSet<Vacacione> Vacaciones { get; set; }
    }
}
