//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.PlanillasRems = new HashSet<PlanillasRem>();
            this.Vacaciones = new HashSet<Vacacione>();
        }
    
        public int IdPersonal { get; set; }
        public string CodPer { get; set; }
        public string DNI { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdUbigeo { get; set; }
        public string CodDistrito { get; set; }
        public Nullable<System.DateTime> FecNac { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<byte> NumHij { get; set; }
        public Nullable<System.DateTime> FecIngreso { get; set; }
        public string Estudios { get; set; }
        public string Grado { get; set; }
        public string NumCol { get; set; }
        public Nullable<int> IdAreaServicio { get; set; }
        public string CodAre { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string CodCar { get; set; }
        public Nullable<int> IdFondoPen { get; set; }
        public string CodFon { get; set; }
        public string TipComAFP { get; set; }
        public string CUSPP { get; set; }
        public string EVida { get; set; }
        public Nullable<decimal> RemBas { get; set; }
        public Nullable<decimal> AsiFam { get; set; }
        public Nullable<decimal> RieCaj { get; set; }
        public string SCTR { get; set; }
        public Nullable<int> HorLab { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FecBaja { get; set; }
        public string EntidadCTS { get; set; }
        public string NumCtaCTS { get; set; }
    
        public virtual AreaServicio AreaServicio { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual FondoPensione FondoPensione { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillasRem> PlanillasRems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacacione> Vacaciones { get; set; }
    }
}
