//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillasRem
    {
        public int IdPlanilla { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public string CodPer { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string CodCar { get; set; }
        public Nullable<int> IdFondoPen { get; set; }
        public string CodFon { get; set; }
        public string TipComAFP { get; set; }
        public Nullable<decimal> RemBas { get; set; }
        public Nullable<decimal> AsiFam { get; set; }
        public Nullable<decimal> Subsidio { get; set; }
        public Nullable<decimal> Gratif { get; set; }
        public Nullable<decimal> RemVac { get; set; }
        public Nullable<decimal> RieCaj { get; set; }
        public Nullable<decimal> Reinte { get; set; }
        public Nullable<decimal> HE { get; set; }
        public Nullable<decimal> OtrIng { get; set; }
        public Nullable<decimal> TotIng { get; set; }
        public Nullable<decimal> PorONP { get; set; }
        public Nullable<decimal> PorApoObl { get; set; }
        public Nullable<decimal> PorPriSeg { get; set; }
        public Nullable<decimal> PorComVar { get; set; }
        public Nullable<decimal> ONP { get; set; }
        public Nullable<decimal> ApoObl { get; set; }
        public Nullable<decimal> PriSeg { get; set; }
        public Nullable<decimal> ComVar { get; set; }
        public Nullable<decimal> Quinta { get; set; }
        public Nullable<decimal> OtrDes { get; set; }
        public Nullable<decimal> TotDes { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> PorEssalud { get; set; }
        public Nullable<decimal> PorSCTR { get; set; }
        public Nullable<decimal> Essalud { get; set; }
        public Nullable<decimal> SCTR { get; set; }
        public Nullable<decimal> TotApo { get; set; }
        public Nullable<int> DiasLab { get; set; }
        public Nullable<int> HorasLab { get; set; }
        public Nullable<System.DateTime> IniVac { get; set; }
        public Nullable<System.DateTime> FinVac { get; set; }
        public Nullable<int> DiasVac { get; set; }
        public Nullable<System.DateTime> IniIncapacidad { get; set; }
        public Nullable<System.DateTime> FinIncapacidad { get; set; }
        public Nullable<int> DiasIncapacidad { get; set; }
        public Nullable<System.DateTime> InicioSinGoceHaber { get; set; }
        public Nullable<System.DateTime> FinSinGoceHaber { get; set; }
        public Nullable<int> DiasSinGoceHaber { get; set; }
        public string Cerrado { get; set; }
        public string TipoPlan { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual FondoPensione FondoPensione { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
