//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacacione
    {
        public int IdVacaciones { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public string CodPer { get; set; }
        public Nullable<System.DateTime> IniProg { get; set; }
        public Nullable<System.DateTime> FinProg { get; set; }
        public Nullable<System.DateTime> IniEje1 { get; set; }
        public Nullable<System.DateTime> FinEje1 { get; set; }
        public Nullable<System.DateTime> IniEje2 { get; set; }
        public Nullable<System.DateTime> FinEje2 { get; set; }
        public Nullable<System.DateTime> IniEje3 { get; set; }
        public Nullable<System.DateTime> FinEje3 { get; set; }
        public string Completo { get; set; }
        public string Obs { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
