//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public int IdMedico { get; set; }
        public string CodMed { get; set; }
        public string DNI { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdUbigeo { get; set; }
        public string CodDistrito { get; set; }
        public Nullable<System.DateTime> FecNac { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string RUC { get; set; }
        public Nullable<System.DateTime> FecIngreso { get; set; }
        public string Grado { get; set; }
        public string NumCol { get; set; }
        public string Sit { get; set; }
        public string RNE { get; set; }
        public Nullable<int> IdEspecialidad1 { get; set; }
        public string CodEsp1 { get; set; }
        public Nullable<int> IdEspecialidad2 { get; set; }
        public string CodEsp2 { get; set; }
        public string Estado { get; set; }
        public string Tipo { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Especialidad Especialidad1 { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
