//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planilla.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaAnalisisVR
    {
        public int IdValReferencial { get; set; }
        public string CodVal { get; set; }
        public string ValReferencial { get; set; }
        public Nullable<int> IdAnalisis { get; set; }
        public string CodAna { get; set; }
    
        public virtual TablaAnalisi TablaAnalisi { get; set; }
    }
}
